name: Deploy website
on:
  push:
    branches:
      - public
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy via FTP
        uses: sebastianpopp/ftp-action@releases/v1
        with:
          host: chi-node5.websitehostserver.net:21
          user: github@trust.invr.info
          password: ${{ secrets.FTP_PASSWORD }}
